#!/bin/bash
# YunoHost restore script for imapfilter_webui
# shellcheck disable=SC2034
source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Restoring files..." --weight=2

ynh_restore_file --origin_path="$install_dir"
chown -R "$app:$app" "$install_dir"

ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_nginx_reload

ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
systemctl daemon-reload

mkdir -p "/var/log/$app"
chown -R "$app:$app" "/var/log/$app"
yunohost service add "$app" --description="imapfilter Web UI" --log="/var/log/$app/$app.log"

ynh_systemd_action --service_name="$app" --action="start" --log_path="systemd" --timeout=30

ynh_script_progression --message="Restore complete!" --last
